### ISSUE TITLE
inquery: does this work with MCMMO rewrite? ie: 2.1.0

### ISSUE THREAD

**Issue by Mrs-Feathers** [jjacobson/Webstats#1]
Does this work with the newest version of MCMMO?

**Comment by jjacobson** [comment]
It depends if they've changed their database structure. I haven't looked at it in a while so you will just have to test it out.

**Comment by Mrs-Feathers** [comment]
Already tested it a while ago since asking this question. It does work with slight modifications. 

———
73, KC1KSG
